language: python
sudo: false
python:
 - 2.6
 - 2.7
 - 3.3
 - 3.4

env:
 - DJANGO_VERSION=1.2.7
 - DJANGO_VERSION=1.3.7
 - DJANGO_VERSION=1.4.19
 - DJANGO_VERSION=1.5.12
 - DJANGO_VERSION=1.6.10
 - DJANGO_VERSION=1.7.4
 - DJANGO_VERSION=1.8

install:
  - travis_retry pip install -q mock==1.0.1 Django==$DJANGO_VERSION coverage coveralls
  - travis_retry pip install --use-mirrors

script:
  - coverage run --source=guardian setup.py test

after_success:
  - coverage report --omit "guardian/compat.py,guardian/testsettings.py" -m guardian/*.py
  - coveralls

notifications:
  irc: "irc.freenode.net#django-guardian"


matrix:
    exclude:
        - python: 3.3
          env: DJANGO_VERSION=1.2.7
        - python: 3.3
          env: DJANGO_VERSION=1.3.7
        - python: 3.3
          env: DJANGO_VERSION=1.4.19
        - python: 3.4
          env: DJANGO_VERSION=1.2.7
        - python: 3.4
          env: DJANGO_VERSION=1.3.7
        - python: 3.4
          env: DJANGO_VERSION=1.4.19
        - python: 2.6
        - env: DJANGO_VERSION=1.7.4
