# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0004_auto_20160202_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupobjectpermission',
            name='permission_expiry',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupobjectpermission',
            name='permission_expiry_0day_email_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='groupobjectpermission',
            name='permission_expiry_30day_email_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='organizationobjectpermission',
            name='permission_expiry',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationobjectpermission',
            name='permission_expiry_0day_email_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='organizationobjectpermission',
            name='permission_expiry_30day_email_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userobjectpermission',
            name='permission_expiry',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userobjectpermission',
            name='permission_expiry_0day_email_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userobjectpermission',
            name='permission_expiry_30day_email_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
