# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-11 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0005_auto_20160921_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupobjectpermission',
            name='object_pk',
            field=models.CharField(db_index=True, max_length=255, verbose_name='object ID'),
        ),
        migrations.AlterField(
            model_name='organizationobjectpermission',
            name='object_pk',
            field=models.CharField(db_index=True, max_length=255, verbose_name='object ID'),
        ),
        migrations.AlterField(
            model_name='userobjectpermission',
            name='object_pk',
            field=models.CharField(db_index=True, max_length=255, verbose_name='object ID'),
        ),
    ]
